### ISSUE TITLE
Failed to build docker containers.

### ISSUE THREAD

**Issue by katesaikishore** [FooBallZ/pulsar#19] opened 2020-04-01 02:54 UTC
Credentials written to web.env, db.env and queue.env files.
Configuration complete.
Do you want to build containers? (y/n) y

Downloading images and dependencies.
This will take a while...

**Failed to build docker containers.**

I have tried in Kali 
Kali: 2019.4
code name: kali-rolling

I have tried on MacOs
MacOS Catalina 10.15.4 

But I am getting the same output.

**Comment by 0x0FB0** [comment] 2020-04-01 08:57
So far I'm unable to reproduce the issue on kali linux (was able to build and run without problems).
Can you attach your install.sh output?

**Comment by Chandram81** [comment] 2020-04-02 16:09
Same issue in ubuntu 18

chandram@hp-probook-440-g5:~/CS_TOOLS/pulsar$ ./install.sh 

Pulsar Installation Script


Before proceeding make sure you have Docker, Docker Compose and ssh-keygen tool
installed on your system.

Do you want to countinue? (y/n) y
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
Generating sandbox RSA ssh keys.
secrets_storage/sandbox_key already exists.
Overwrite (y/n)? y

Generated default service credentials.
Store them somewhere safe.


Django Admin user:		admin
Django Admin password:		456ddf770befcfff6aa9c480

RabbitMQ queue user:		queue_admin
RabbitMQ queue password:	cbce7c7a102aa78d8b39a758

MySQL database user:		pulsar_db_user
MySQL database password:	d8ff4fdc7b919e7fa24f1a38


Credentials written to web.env, db.env and queue.env files.
Configuration complete.
Do you want to build containers? (y/n) y

Downloading images and dependencies.
This will take a while...

Failed to build docker containers.
![image](https://user-images.githubusercontent.com/4585651/78271915-66ae5a00-752a-11ea-8eee-38c2e7cf0b65.png)

**Comment by 0x0FB0** [comment] 2020-04-02 21:32
Thanks for the input.

So far it seems that this issue is related to the docker-compose version.

Can you try from scratch with **dev** branch?
Please paste in output again, it should be more verbose this time.

```
git clone -b dev https://github.com/FooBallZ/pulsar
```

**Comment by katesaikishore** [comment] 2020-04-03 02:32
Yeah I too got the same output 
https://github.com/FooBallZ/pulsar/issues/19#issuecomment-607940666

Let me try the dev branch

**Comment by katesaikishore** [comment] 2020-04-03 02:51
git clone -b https://github.com/FooBallZ/pulsar
The flag -b doesn't work.
I have done 
git fetch https://github.com/FooBallZ/pulsar master
But I am getting the same result while running 
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 818 (delta 7), reused 11 (delta 5), pack-reused 789
Receiving objects: 100% (818/818), 11.91 MiB | 3.89 MiB/s, done.
Resolving deltas: 100% (400/400), done.
From https://github.com/FooBallZ/pulsar
 * branch            master     -> FETCH_HEAD


Generated default service credentials.
Store them somewhere safe.


Django Admin user:		admin
Django Admin password:		0a1964134c7a1a5051af31c9

RabbitMQ queue user:		queue_admin
RabbitMQ queue password:	432a2a7a219ec270639f51a6

MySQL database user:		pulsar_db_user
MySQL database password:	e02d6270af421772555ad877


Credentials written to web.env, db.env and queue.env files.
Configuration complete.
Do you want to build containers? (y/n) y

Downloading images and dependencies.
This will take a while...

Failed to build docker containers.

**Comment by 0x0FB0** [comment] 2020-04-03 06:15
```
git clone -b dev https://github.com/FooBallZ/pulsar
```

**Comment by 0x0FB0** [comment] 2020-04-03 08:02
new v1 release have just been published, you may want to test it

**Comment by katesaikishore** [comment] 2020-04-03 14:18
Successfully built e86513798e3a
Successfully tagged pulsar_web:latest

Build finished!
Do you want to start Pulsar now? (y/n)

yeah it works thanks!

**Comment by 0x0FB0** [comment] 2020-04-03 14:59
Awesome! Closing the issue

**Closed as completed by 0x0FB0** 2020-04-03 14:59 UTC
Labels: bug, question, needs more info
